### ISSUE TITLE
Error reading retrieved json files

### ISSUE THREAD

**Issue by rgalginaitis** [RyanLynchUF/auction-aid#5]
## Description of Issue
Console shows that the code is able to pull historical data (since 2010) but then immediately has issues reading the files
> Error reading file espn-81479-2009.json: str.__new__(X): X is not a type object (str)

Since files cannot be read, the script throws an exception on line 120, in generate_player_features because included_past_seasons is empty
```
input_features['prev_year_bid_amt'] = input_features['bid_amt_' + str(max(included_past_seasons))]                                                                                                                
ValueError: max() iterable argument is empty
```

#### Fantasy Football Platform
ESPN

#### League ID
81479

#### Operating System
Windows 10

#### Other

**Comment by rgalginaitis** [comment]
Weirdly, the 2018 file can be read
> Successfully read espn-81479-2018.json

but all the rest throw the same error


>Error reading file espn-81479-2019.json: str.__new__(X): X is not a type object (str)

**Comment by RyanLynchUF** [comment]
It looks like there was an issue with the serialization, which was causing the error when deserializing the data.  It should be fixed now!  I was able to successfully run the tool for the league ID you provided.  Let me know if you run into any other issues, though.

**Comment by rgalginaitis** [comment]
The fix worked but now I'm getting another error.

```
2024-12-03 12:03:41,419 - statistical_analysis - INFO - Roster and bench counts exceeded available player projections.  Returning truncated bench count results.
←[32mINFO←[0m:     127.0.0.1:0 - "←[1mPOST /api/generate-auction-aid HTTP/1.1←[0m" ←[91m500 Internal Server Error←[0m
←[31mERROR←[0m:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Python312\Lib\site-packages\pandas\core\indexes\base.py", line 3805, in get_loc
    return self._engine.get_loc(casted_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "index.pyx", line 167, in pandas._libs.index.IndexEngine.get_loc
  File "index.pyx", line 196, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\\_libs\\hashtable_class_helper.pxi", line 7081, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\\_libs\\hashtable_class_helper.pxi", line 7089, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'vbd_2009'
```

Stack trace points to this function call in main.py
```training_player_features = features.generate_player_features(input_player_features, past_seasons_for_training, statistic_for_vorp_calculation).reset_index()```

**Comment by RyanLynchUF** [comment]
This is because your league is older than the available FantasyPros historical data, which goes back to 2013.  For a quick fix, I updated the code to just only consider the league data from 2013 onward, but I will think through a cleaner approach in the future.  This approach should work well enough for now, though, since your league's most recent tendencies are the most important anyway!

Thanks for your patience working through these with me.

**Comment by rgalginaitis** [comment]
Aha! That worked! Happy to help test things out.
